# The meta-data of site.
# © 2017-2019 Cotes Chung
# MIT License

ga_id: "UA-145932385-1"           # Change to your Google Analytics ID

disqus_shortname: "chirpy-demo"   # Change to your Disqus shortname.

first_run: 2019                   # The year your website was first run.

uri: "https://chirpy.cotes.info"  # Replace with your domain, e.g. "https://username.github.io"
